### ISSUE TITLE
Replace prismadb Queries with Wundergraph

### ISSUE THREAD

**Issue by srizvi** [and-voila/and-voila#22]
**This is blocked by #21.**

### Intro 
Right now, we're using prisma to query the database i.e. `import prismadb from 'lib/prismadb';`. 

We need to replace these with wundergraph.

## Functions

- apps/dash/lib/api-limit.ts
- apps/dash/lib/subscription.ts

## Functions are called here
- apps/dash/app/api/stripe/route.ts
- apps/dash/app/api/webhook/route.ts

## Task list

- [x] #61
- [x] #62
- [x] #63
- [x] #64
- [ ] Confirm checkApiLimit function working globally
- [ ] Confirm increaseApiLimit function working globally
- [ ] Confirm checkSubscription function working globally
