### ISSUE TITLE
Create Persona Prototypes

### ISSUE THREAD

**Issue by srizvi** [and-voila/and-voila#24]
### Intro
Using previous analysis, create a prototype for Ambreen, Rebekah, or Sam's writing that can be incorporated into Samuel's workflow for #23.

## Task List

- [ ] Add search filters
- [ ] Persona form and integration
- [ ] Create Persona API
- [ ] Create Persona list
- [ ] Integrate to Chat UI
- [ ] Integrate to Upstash
