### ISSUE TITLE
Pricing Configuration

### ISSUE THREAD

**Issue by srizvi** [and-voila/and-voila#28]
### Intro
We're going to be using metered and per seat billing for the app.

### Reference
We will be using [Tier](https://tier.run) integrated to Stripe.

## Task List
- [ ] Define pricing model(s)
- [ ] Create plans and integrate
- [ ] Add to front-end
