### ISSUE TITLE
check and update front end styles globally

### ISSUE THREAD

**Issue by srizvi** [and-voila/and-voila#29]
### Intro
Need to check the front end across all screen sizes. 

### Reference
https://codepen.io/chris__sev/pen/MWmdZOw

## Task List
- [ ] Temporarily add RWD utility to app
- [ ] Check front-end display on all screens
- [ ] Fix issues, if any
- [ ] Remove RWD utility
